FROM node:10.15.3-alpine

WORKDIR '/var/www/app'
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)


COPY package*.json ./

RUN npm install --only=production

RUN npm install -g http-server

# If you are building your code for production

# Bundle app source
COPY . .
EXPOSE 5000
ENV NODE_ENV production
RUN npm run build
CMD [ "http-server" "./build", "-p", "5000"]
